version: '3'
services:
    network:
        image: openmined/grid-gateway:latest
        build: .
        environment:
                - NODE_ID=Bob
                - GRID_PORT=5000
                - SECRET_KEY=ineedtoputasecrethere
                - DATABASE_URL=sqlite:///databasegateway.db
        ports:
        - 5000:5000
    bob:
        image: openmined/grid-node:latest
        environment:
                - ID=Bob
                - ADDRESS=http://bob:3000/
                - PORT=3000
        depends_on:
                - "network"
        ports:
        - 3000:3000
    alice:
        image: openmined/grid-node:latest
        environment:
                - ID=Alice
                - ADDRESS=http://alice:3001/
                - PORT=3001
        depends_on:
                - "network"
        ports:
        - 3001:3001
    bill:
        image: openmined/grid-node:latest
        environment:
                - ID=Bill
                - ADDRESS=http://bill:3002/
                - PORT=3002
        depends_on:
                - "network"
        ports:
        - 3002:3002
    james:
        image: openmined/grid-node:latest
        environment:
                - ID=James
                - ADDRESS=http://james:3003/
                - PORT=3003
        depends_on:
                - "network"
        ports:
        - 3003:3003
